import type { MasterFileTagRecord, ToothStatusRecord } from './masterFileDirectoryService';

export const defaultToothStatuses: ToothStatusRecord[] = [
  {
    id: 'status-clear',
    code: 'CLR',
    name: 'Clear',
    description: 'Remove tooth marking',
    color: '#ffffff',
    active: true,
    sortOrder: 0,
    behavior: 'clear',
    updatedAt: '2026-07-29'
  },
  {
    id: 'status-cavity',
    code: 'CV',
    name: 'Cavity',
    description: 'Tooth decay or caries',
    color: '#ef4444',
    active: true,
    sortOrder: 1,
    behavior: 'surface',
    updatedAt: '2026-07-29'
  },
  {
    id: 'status-okpasta',
    code: 'OK',
    name: 'OK/Pasta',
    description: 'Existing restoration or filling',
    color: '#4f7bf5',
    active: true,
    sortOrder: 2,
    behavior: 'surface',
    updatedAt: '2026-07-29'
  },
  {
    id: 'status-missing',
    code: 'MIS',
    name: 'Missing',
    description: 'Tooth is absent',
    color: '#111827',
    active: true,
    sortOrder: 3,
    behavior: 'whole-tooth',
    updatedAt: '2026-07-29'
  },
  {
    id: 'status-crown',
    code: 'CR',
    name: 'Crown',
    description: 'Crown restoration present',
    color: '#f59e0b',
    active: true,
    sortOrder: 4,
    behavior: 'surface',
    updatedAt: '2026-07-29'
  },
  {
    id: 'status-root-canal',
    code: 'RCT',
    name: 'Root Canal',
    description: 'Root canal treated tooth',
    color: '#16a34a',
    active: true,
    sortOrder: 5,
    behavior: 'surface',
    updatedAt: '2026-07-29'
  },
  {
    id: 'status-extraction',
    code: 'EXT',
    name: 'Extraction',
    description: 'Extraction indicated',
    color: '#f97316',
    active: true,
    sortOrder: 6,
    behavior: 'surface',
    updatedAt: '2026-07-29'
  }
];

export const defaultMasterFileTagRecords: MasterFileTagRecord[] = [
  { id: 'cond-1', categoryId: 'tooth-condition', code: '/', name: 'Present Teeth', description: 'Present Teeth', active: true, sortOrder: 0, updatedAt: '2026-07-29' },
  { id: 'cond-2', categoryId: 'tooth-condition', code: 'M', name: 'Missing Due to Caries', description: 'Missing Due to Caries', active: true, sortOrder: 1, updatedAt: '2026-07-29' },
  { id: 'cond-3', categoryId: 'tooth-condition', code: 'MO', name: 'Missing Other Causes', description: 'Missing Other Causes', active: true, sortOrder: 2, updatedAt: '2026-07-29' },
  { id: 'cond-4', categoryId: 'tooth-condition', code: 'IM', name: 'Impacted', description: 'Impacted', active: true, sortOrder: 3, updatedAt: '2026-07-29' },
  { id: 'cond-5', categoryId: 'tooth-condition', code: 'SP', name: 'Supernumerary', description: 'Supernumerary', active: true, sortOrder: 4, updatedAt: '2026-07-29' },
  { id: 'cond-6', categoryId: 'tooth-condition', code: 'RF', name: 'Root Fragment', description: 'Root Fragment', active: true, sortOrder: 5, updatedAt: '2026-07-29' },
  { id: 'cond-7', categoryId: 'tooth-condition', code: 'UN', name: 'Unerupted', description: 'Unerupted', active: true, sortOrder: 6, updatedAt: '2026-07-29' },
  { id: 'cond-8', categoryId: 'tooth-condition', code: 'PT', name: 'Partially Erupted', description: 'Partially Erupted', active: true, sortOrder: 7, updatedAt: '2026-07-29' },
  { id: 'cond-9', categoryId: 'tooth-condition', code: 'D', name: 'Decayed', description: 'Decayed', active: true, sortOrder: 8, updatedAt: '2026-07-29' },
  { id: 'cond-10', categoryId: 'tooth-condition', code: 'RCT', name: 'Root Canal Treatment', description: 'Root Canal Treatment', active: true, sortOrder: 9, updatedAt: '2026-07-29' },

  { id: 'pros-1', categoryId: 'prosthodontics', code: 'MC', name: 'Metal Crown', description: 'Metal Crown', active: true, sortOrder: 0, updatedAt: '2026-07-29' },
  { id: 'pros-2', categoryId: 'prosthodontics', code: 'PJ', name: 'Jacket Crown', description: 'Jacket Crown', active: true, sortOrder: 1, updatedAt: '2026-07-29' },
  { id: 'pros-3', categoryId: 'prosthodontics', code: 'AM', name: 'Amalgam Filling', description: 'Amalgam Filling', active: true, sortOrder: 2, updatedAt: '2026-07-29' },
  { id: 'pros-4', categoryId: 'prosthodontics', code: 'LCF', name: 'Composite Filling', description: 'Composite Filling', active: true, sortOrder: 3, updatedAt: '2026-07-29' },
  { id: 'pros-5', categoryId: 'prosthodontics', code: 'PORJC', name: 'Porcelain Crown', description: 'Porcelain Crown', active: true, sortOrder: 4, updatedAt: '2026-07-29' },
  { id: 'pros-6', categoryId: 'prosthodontics', code: 'AB', name: 'Abutment', description: 'Abutment', active: true, sortOrder: 5, updatedAt: '2026-07-29' },
  { id: 'pros-7', categoryId: 'prosthodontics', code: 'ATT', name: 'Attachment', description: 'Attachment', active: true, sortOrder: 6, updatedAt: '2026-07-29' },
  { id: 'pros-8', categoryId: 'prosthodontics', code: 'P', name: 'Pontic', description: 'Pontic', active: true, sortOrder: 7, updatedAt: '2026-07-29' },
  { id: 'pros-9', categoryId: 'prosthodontics', code: 'IC', name: 'Inlay', description: 'Inlay', active: true, sortOrder: 8, updatedAt: '2026-07-29' },
  { id: 'pros-10', categoryId: 'prosthodontics', code: 'IMP', name: 'Implant', description: 'Implant', active: true, sortOrder: 9, updatedAt: '2026-07-29' },
  { id: 'pros-11', categoryId: 'prosthodontics', code: 'S', name: 'Sealants', description: 'Sealants', active: true, sortOrder: 10, updatedAt: '2026-07-29' },
  { id: 'pros-12', categoryId: 'prosthodontics', code: 'RM', name: 'Removal Denture', description: 'Removal Denture', active: true, sortOrder: 11, updatedAt: '2026-07-29' },
  { id: 'pros-13', categoryId: 'prosthodontics', code: 'GI', name: 'Glass Ionomer', description: 'Glass Ionomer', active: true, sortOrder: 12, updatedAt: '2026-07-29' },
  { id: 'pros-14', categoryId: 'prosthodontics', code: 'V', name: 'Veneer', description: 'Veneer', active: true, sortOrder: 13, updatedAt: '2026-07-29' },
  { id: 'pros-15', categoryId: 'prosthodontics', code: 'TF', name: 'Temporary Filling', description: 'Temporary Filling', active: true, sortOrder: 14, updatedAt: '2026-07-29' },

  { id: 'surg-1', categoryId: 'dental-surgery', code: 'X', name: 'Extraction Due to Caries', description: 'Extraction Due to Caries', active: true, sortOrder: 0, updatedAt: '2026-07-29' },
  { id: 'surg-2', categoryId: 'dental-surgery', code: 'XO', name: 'Extraction Other Causes', description: 'Extraction Other Causes', active: true, sortOrder: 1, updatedAt: '2026-07-29' },

  { id: 'xray-1', categoryId: 'xray-scan-items', code: 'PANO', name: 'Panoramic', description: 'Panoramic', active: true, sortOrder: 0, updatedAt: '2026-07-29' },
  { id: 'xray-2', categoryId: 'xray-scan-items', code: 'CEPHA', name: 'Cephalometric', description: 'Cephalometric', active: true, sortOrder: 1, updatedAt: '2026-07-29' },
  { id: 'xray-3', categoryId: 'xray-scan-items', code: 'OCC', name: 'Occlusal', description: 'Occlusal', active: true, sortOrder: 2, updatedAt: '2026-07-29' },
  { id: 'xray-4', categoryId: 'xray-scan-items', code: 'PERI', name: 'Periapical', description: 'Periapical', active: true, sortOrder: 3, updatedAt: '2026-07-29' },

  {
    id: 'rx-template-1',
    categoryId: 'prescription-templates',
    code: 'RX001',
    name: 'Post-Extraction Antibiotic & Painkiller',
    description: 'Standard post-op medication template',
    details: 'Amoxicillin Trihydrate 500mg\nTake 1 capsule every 8 hours for 7 days\n\nMefenamic Acid 500mg\nTake 1 tablet every 8 hours as needed for pain.',
    active: true,
    sortOrder: 0,
    updatedAt: '2026-07-12'
  },
  {
    id: 'rx-template-2',
    categoryId: 'prescription-templates',
    code: 'RX002',
    name: 'Orthodontic Soreness Management',
    description: 'Standard post-adjustment discomfort template',
    details: 'Paracetamol 500mg\nTake 1 tablet every 4 to 6 hours as needed for dental soreness.',
    active: true,
    sortOrder: 1,
    updatedAt: '2026-07-12'
  },
  {
    id: 'rx-template-3',
    categoryId: 'prescription-templates',
    code: 'RX003',
    name: 'Root Canal Antibiotic Treatment',
    description: 'Standard severe infection treatment prescription',
    details: 'Co-Amoxiclav 625mg\nTake 1 tablet every 12 hours for 7 days\n\nMefenamic Acid 500mg\nTake 1 tablet every 8 hours as needed for pain.',
    active: true,
    sortOrder: 2,
    updatedAt: '2026-07-12'
  },
  { id: 'appliance-1', categoryId: 'intra-oral-appliance', code: 'RA001', name: 'Orthodontic', description: '-', details: '-', active: true, sortOrder: 0, updatedAt: '2026-07-12' },
  { id: 'appliance-2', categoryId: 'intra-oral-appliance', code: 'RA002', name: 'Stayplate', description: '-', details: '-', active: true, sortOrder: 1, updatedAt: '2026-07-12' },
  { id: 'appliance-3', categoryId: 'intra-oral-appliance', code: 'RA003', name: 'Other', description: '-', details: '-', active: true, sortOrder: 2, updatedAt: '2026-07-12' },
  { id: 'occlusion-1', categoryId: 'occlusion-index', code: 'RO001', name: 'Class (Molar)', description: '-', details: '-', active: true, sortOrder: 0, updatedAt: '2026-07-12' },
  { id: 'occlusion-2', categoryId: 'occlusion-index', code: 'RO002', name: 'Overjet', description: '-', details: '-', active: true, sortOrder: 1, updatedAt: '2026-07-12' },
  { id: 'occlusion-3', categoryId: 'occlusion-index', code: 'RO003', name: 'Overbite', description: '-', details: '-', active: true, sortOrder: 2, updatedAt: '2026-07-12' },
  { id: 'occlusion-4', categoryId: 'occlusion-index', code: 'RO004', name: 'Midline Deviation', description: '-', details: '-', active: true, sortOrder: 3, updatedAt: '2026-07-12' },
  { id: 'occlusion-5', categoryId: 'occlusion-index', code: 'RO005', name: 'Crossbite', description: '-', details: '-', active: true, sortOrder: 4, updatedAt: '2026-07-12' },
  { id: 'psr-1', categoryId: 'periodontal-psr', code: 'PS001', name: 'Gingivitis', description: '-', details: '-', active: true, sortOrder: 0, updatedAt: '2026-07-12' },
  { id: 'psr-2', categoryId: 'periodontal-psr', code: 'PS002', name: 'Early Periodontitis', description: '-', details: '-', active: true, sortOrder: 1, updatedAt: '2026-07-12' },
  { id: 'psr-3', categoryId: 'periodontal-psr', code: 'PS003', name: 'Moderate Periodontitis', description: '-', details: '-', active: true, sortOrder: 2, updatedAt: '2026-07-12' },
  { id: 'psr-4', categoryId: 'periodontal-psr', code: 'PS004', name: 'Advanced Periodontitis', description: '-', details: '-', active: true, sortOrder: 3, updatedAt: '2026-07-12' },
  { id: 'psr-5', categoryId: 'periodontal-psr', code: 'PS005', name: 'Presence of Calculus Deposit', description: '-', details: '-', active: true, sortOrder: 4, updatedAt: '2026-07-12' },
  { id: 'psr-6', categoryId: 'periodontal-psr', code: 'PS006', name: 'Good Oral Hygiene', description: '-', details: '-', active: true, sortOrder: 5, updatedAt: '2026-07-12' },
  { id: 'tmj-1', categoryId: 'tmj-assessment', code: 'RTMD001', name: 'Clenching', description: '-', details: '-', active: true, sortOrder: 0, updatedAt: '2026-07-12' },
  { id: 'tmj-2', categoryId: 'tmj-assessment', code: 'RTMD002', name: 'Clicking', description: '-', details: '-', active: true, sortOrder: 1, updatedAt: '2026-07-12' },
  { id: 'tmj-3', categoryId: 'tmj-assessment', code: 'RTMD003', name: 'Trismus', description: '-', details: '-', active: true, sortOrder: 2, updatedAt: '2026-07-12' },
  { id: 'tmj-4', categoryId: 'tmj-assessment', code: 'RTMD004', name: 'Muscle Spasm', description: '-', details: '-', active: true, sortOrder: 3, updatedAt: '2026-07-12' },

  { id: 'recall-1', categoryId: 'recall-reasons', code: 'RR001', name: 'Orthodontic Adjustment', description: 'Routine braces adjustment recall.', active: true, sortOrder: 0, updatedAt: '2026-07-12', category: 'orthodontic', defaultRecallWindow: '30 days' },
  { id: 'recall-2', categoryId: 'recall-reasons', code: 'RR002', name: 'Post-Extraction Review', description: 'Healing and extraction site review.', active: true, sortOrder: 1, updatedAt: '2026-07-12', category: 'surgical', defaultRecallWindow: '7 days' },
  { id: 'recall-3', categoryId: 'recall-reasons', code: 'RR003', name: 'Root Canal Follow-up', description: 'RCT monitoring and reassessment.', active: true, sortOrder: 2, updatedAt: '2026-07-12', category: 'endodontic', defaultRecallWindow: '14 days' },
  { id: 'recall-4', categoryId: 'recall-reasons', code: 'RR004', name: 'General Checkup', description: 'Routine dental checkup recall.', active: true, sortOrder: 3, updatedAt: '2026-07-12', category: 'preventive', defaultRecallWindow: '180 days' },
  { id: 'recall-5', categoryId: 'recall-reasons', code: 'RR005', name: 'Crown/Bridge Adjustment', description: 'Adjustment review for crown or bridge fit.', active: true, sortOrder: 4, updatedAt: '2026-07-12', category: 'prosthodontic', defaultRecallWindow: '14 days' },
  { id: 'recall-6', categoryId: 'recall-reasons', code: 'RR006', name: 'Periodontal Maintenance', description: 'Maintenance visit for periodontal monitoring.', active: true, sortOrder: 5, updatedAt: '2026-07-12', category: 'periodontal', defaultRecallWindow: '90 days' },
  { id: 'recall-7', categoryId: 'recall-reasons', code: 'RR007', name: 'Other', description: 'Fallback recall reason for custom scheduling.', active: true, sortOrder: 6, updatedAt: '2026-07-12', category: 'other', defaultRecallWindow: 'Custom' },

  { id: 'svc-1', categoryId: 'clinical-services', code: 'SVC001', name: 'Consultation Fee', description: '-', details: 'PHP 500.00', active: true, sortOrder: 0, updatedAt: '2026-07-12', defaultPrice: 500, treatmentCategory: 'Consultation' },
  { id: 'svc-2', categoryId: 'clinical-services', code: 'SVC002', name: 'Pediatric Extraction (Anterior)', description: 'Bata Front Teeth', details: 'PHP 1,000.00', active: true, sortOrder: 1, updatedAt: '2026-07-12', defaultPrice: 1000, treatmentCategory: 'Extraction' },
  { id: 'svc-3', categoryId: 'clinical-services', code: 'SVC003', name: 'Composite Filling (Mild/Shallow)', description: '-', details: 'PHP 1,000.00', active: true, sortOrder: 2, updatedAt: '2026-07-12', defaultPrice: 1000, treatmentCategory: 'Restorative' },
  { id: 'svc-4', categoryId: 'clinical-services', code: 'SVC004', name: 'Oral Prophylaxis with Topical Fluoride', description: '-', details: 'PHP 1,800.00', active: true, sortOrder: 3, updatedAt: '2026-07-12', defaultPrice: 1800, treatmentCategory: 'Preventive' },
  { id: 'svc-5', categoryId: 'clinical-services', code: 'SVC005', name: 'Oral Prophylaxis (Mild)', description: 'Mild Calculus Deposit', details: 'PHP 1,000.00', active: true, sortOrder: 4, updatedAt: '2026-07-12', defaultPrice: 1000, treatmentCategory: 'Preventive' },
  { id: 'svc-6', categoryId: 'clinical-services', code: 'SVC006', name: 'Oral Prophylaxis (Moderate)', description: '-', details: 'PHP 1,500.00', active: true, sortOrder: 5, updatedAt: '2026-07-12', defaultPrice: 1500, treatmentCategory: 'Preventive' },
  { id: 'svc-7', categoryId: 'clinical-services', code: 'SVC007', name: 'Oral Prophylaxis (Severe)', description: '-', details: 'PHP 2,500.00', active: true, sortOrder: 6, updatedAt: '2026-07-12', defaultPrice: 2500, treatmentCategory: 'Preventive' },
  { id: 'svc-8', categoryId: 'clinical-services', code: 'SVC008', name: 'Composite Filling (Moderate)', description: '-', details: 'PHP 1,500.00', active: true, sortOrder: 7, updatedAt: '2026-07-12', defaultPrice: 1500, treatmentCategory: 'Restorative' },
  { id: 'svc-9', categoryId: 'clinical-services', code: 'SVC009', name: 'Composite Veneers', description: '-', details: 'PHP 7,000.00', active: true, sortOrder: 8, updatedAt: '2026-07-12', defaultPrice: 7000, treatmentCategory: 'Cosmetic' },
  { id: 'svc-10', categoryId: 'clinical-services', code: 'SVC010', name: 'Pediatric Extraction (Posterior)', description: 'Bata Pangil to Bagang na Ngipin', details: 'PHP 1,500.00', active: true, sortOrder: 9, updatedAt: '2026-07-12', defaultPrice: 1500, treatmentCategory: 'Extraction' },
  { id: 'svc-11', categoryId: 'clinical-services', code: 'SVC011', name: 'Extraction (Anterior)', description: '-', details: 'PHP 1,000.00', active: true, sortOrder: 10, updatedAt: '2026-07-12', defaultPrice: 1000, treatmentCategory: 'Extraction' },
  { id: 'svc-12', categoryId: 'clinical-services', code: 'SVC012', name: 'Extraction (Posterior)', description: '-', details: 'PHP 1,500.00', active: true, sortOrder: 11, updatedAt: '2026-07-12', defaultPrice: 1500, treatmentCategory: 'Extraction' },
  { id: 'svc-13', categoryId: 'clinical-services', code: 'SVC013', name: 'With Surgery Machine', description: '-', details: 'PHP 1,000.00', active: true, sortOrder: 12, updatedAt: '2026-07-12', defaultPrice: 1000, treatmentCategory: 'Surgical Support' },
  { id: 'svc-14', categoryId: 'clinical-services', code: 'SVC014', name: 'Extraction (Upper Wisdom Tooth)', description: '-', details: 'PHP 5,000.00', active: true, sortOrder: 13, updatedAt: '2026-07-12', defaultPrice: 5000, treatmentCategory: 'Extraction' },
  { id: 'svc-15', categoryId: 'clinical-services', code: 'SVC015', name: 'Follow-up Check-up', description: '-', details: 'PHP 600.00', active: true, sortOrder: 14, updatedAt: '2026-07-12', defaultPrice: 600, treatmentCategory: 'Consultation' },
  { id: 'svc-16', categoryId: 'clinical-services', code: 'SVC016', name: 'Consultation (Labxpert-Yazaki)', description: '-', details: 'PHP 200.00', active: true, sortOrder: 15, updatedAt: '2026-07-12', defaultPrice: 200, treatmentCategory: 'Consultation' },
  { id: 'svc-17', categoryId: 'clinical-services', code: 'SVC017', name: 'Consultation (Labxpert-Liwayway)', description: '-', details: 'PHP 150.00', active: true, sortOrder: 16, updatedAt: '2026-07-12', defaultPrice: 150, treatmentCategory: 'Consultation' },
  { id: 'svc-18', categoryId: 'clinical-services', code: 'SVC018', name: 'Braces Impression', description: '-', details: 'PHP 5,000.00', active: true, sortOrder: 17, updatedAt: '2026-07-12', defaultPrice: 5000, treatmentCategory: 'Orthodontic' },
  { id: 'svc-19', categoryId: 'clinical-services', code: 'SVC019', name: 'Adjust Braces 1', description: '-', details: 'PHP 1,500.00', active: true, sortOrder: 18, updatedAt: '2026-07-12', defaultPrice: 1500, treatmentCategory: 'Orthodontic' },
  { id: 'svc-20', categoryId: 'clinical-services', code: 'SVC020', name: 'Adjust Braces 2', description: '-', details: 'PHP 1,000.00', active: true, sortOrder: 19, updatedAt: '2026-07-12', defaultPrice: 1000, treatmentCategory: 'Orthodontic' },
  { id: 'svc-21', categoryId: 'clinical-services', code: 'SVC021', name: 'Repaste Bracket', description: '-', details: 'PHP 250.00', active: true, sortOrder: 20, updatedAt: '2026-07-12', defaultPrice: 250, treatmentCategory: 'Orthodontic' },
  { id: 'svc-22', categoryId: 'clinical-services', code: 'SVC022', name: 'Replace Bracket', description: '-', details: 'PHP 500.00', active: true, sortOrder: 21, updatedAt: '2026-07-12', defaultPrice: 500, treatmentCategory: 'Orthodontic' },
  { id: 'svc-23', categoryId: 'clinical-services', code: 'SVC023', name: 'Sealant', description: '-', details: 'PHP 1,000.00', active: true, sortOrder: 22, updatedAt: '2026-07-12', defaultPrice: 1000, treatmentCategory: 'Preventive' },
  { id: 'svc-24', categoryId: 'clinical-services', code: 'SVC024', name: 'Periapical Radiograph', description: '-', details: 'PHP 700.00', active: true, sortOrder: 23, updatedAt: '2026-07-12', defaultPrice: 700, treatmentCategory: 'Diagnostic' },
  { id: 'svc-25', categoryId: 'clinical-services', code: 'SVC025', name: 'Odontectomy (Easy)', description: '-', details: 'PHP 5,000.00', active: true, sortOrder: 24, updatedAt: '2026-07-12', defaultPrice: 5000, treatmentCategory: 'Surgical' },
  { id: 'svc-26', categoryId: 'clinical-services', code: 'SVC026', name: 'Consultation (Labxpert-CAVSU)', description: '-', details: 'PHP 200.00', active: true, sortOrder: 25, updatedAt: '2026-07-12', defaultPrice: 200, treatmentCategory: 'Consultation' },
  { id: 'svc-27', categoryId: 'clinical-services', code: 'SVC027', name: 'Consultation (Labxpert-Lyceum)', description: '-', details: 'PHP 200.00', active: true, sortOrder: 26, updatedAt: '2026-07-12', defaultPrice: 200, treatmentCategory: 'Consultation' },
  { id: 'svc-28', categoryId: 'clinical-services', code: 'SVC028', name: 'Consultation (Labxpert-DepEd)', description: '-', details: 'PHP 200.00', active: true, sortOrder: 27, updatedAt: '2026-07-12', defaultPrice: 200, treatmentCategory: 'Consultation' },
  { id: 'svc-29', categoryId: 'clinical-services', code: 'SVC029', name: 'Consultation (Labxpert)', description: '-', details: 'PHP 200.00', active: true, sortOrder: 28, updatedAt: '2026-07-12', defaultPrice: 200, treatmentCategory: 'Consultation' },
  { id: 'svc-30', categoryId: 'clinical-services', code: 'SVC030', name: 'Dental Certificate', description: '-', details: 'PHP 100.00', active: true, sortOrder: 29, updatedAt: '2026-07-12', defaultPrice: 100, treatmentCategory: 'Document' },
  { id: 'svc-31', categoryId: 'clinical-services', code: 'SVC031', name: 'Braces Removal', description: '-', details: 'PHP 3,500.00', active: true, sortOrder: 30, updatedAt: '2026-07-12', defaultPrice: 3500, treatmentCategory: 'Orthodontic' },
  { id: 'svc-32', categoryId: 'clinical-services', code: 'SVC032', name: 'Impression for Denture', description: '-', details: 'PHP 0.00', active: true, sortOrder: 31, updatedAt: '2026-07-12', defaultPrice: 0, treatmentCategory: 'Prosthodontic' },

  { id: 'med-1', categoryId: 'medicine-catalog', code: 'MED001', name: 'Amoxicillin Trihydrate 500mg (Amoxil)', description: 'Localized Infection', active: true, sortOrder: 0, updatedAt: '2026-07-12', genericName: 'Amoxicillin', indication: 'Localized Infection', dosage: '500mg' },
  { id: 'med-2', categoryId: 'medicine-catalog', code: 'MED002', name: 'Mefenamic Acid 500mg (Ponstan SF)', description: 'Pain Reliever', active: true, sortOrder: 1, updatedAt: '2026-07-12', genericName: 'Mefenamic Acid', indication: 'Pain Reliever', dosage: '500mg' },
  { id: 'med-3', categoryId: 'medicine-catalog', code: 'MED003', name: 'Tranexamic Acid 500mg (Hemostan)', description: 'For Bleeding', active: true, sortOrder: 2, updatedAt: '2026-07-12', genericName: 'Tranexamic Acid', indication: 'For Bleeding', dosage: '500mg' },
  { id: 'med-4', categoryId: 'medicine-catalog', code: 'MED004', name: 'Paracetamol 500mg (Biogesic)', description: 'Pain Reliever', active: true, sortOrder: 3, updatedAt: '2026-07-12', genericName: 'Paracetamol', indication: 'Pain Reliever', dosage: '500mg' },
  { id: 'med-5', categoryId: 'medicine-catalog', code: 'MED005', name: 'Co-Amoxiclav 625mg (Augmentin)', description: 'Broad Infection', active: true, sortOrder: 4, updatedAt: '2026-07-12', genericName: 'Co-Amoxiclav', indication: 'Broad Infection', dosage: '625mg' },
  { id: 'med-6', categoryId: 'medicine-catalog', code: 'MED006', name: 'Chlorhexidine (Orahex AF)', description: 'Mouthwash', active: true, sortOrder: 5, updatedAt: '2026-07-12', genericName: 'Chlorhexidine', indication: 'Mouthwash' },
  { id: 'med-7', categoryId: 'medicine-catalog', code: 'MED007', name: 'Clindamycin 300mg', description: 'Alternative for patients allergic to Amoxicillin', active: true, sortOrder: 6, updatedAt: '2026-07-12', genericName: 'Clindamycin', indication: 'Alternative for patients allergic to Amoxicillin', dosage: '300mg' },

  { id: 'mc-1', categoryId: 'medical-conditions', code: 'MC001', name: 'High Blood Pressure', description: '-', active: true, sortOrder: 0, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-2', categoryId: 'medical-conditions', code: 'MC002', name: 'Low Blood Pressure', description: '-', active: true, sortOrder: 1, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-3', categoryId: 'medical-conditions', code: 'MC003', name: 'Epilepsy or Convulsion', description: '-', active: true, sortOrder: 2, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-4', categoryId: 'medical-conditions', code: 'MC004', name: 'AIDS/HIV Infection', description: '-', active: true, sortOrder: 3, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-5', categoryId: 'medical-conditions', code: 'MC005', name: 'Sexually Transmitted Disease', description: '-', active: true, sortOrder: 4, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-6', categoryId: 'medical-conditions', code: 'MC006', name: 'Stomach Troubles or Ulcers', description: '-', active: true, sortOrder: 5, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-7', categoryId: 'medical-conditions', code: 'MC007', name: 'Fainting Seizures', description: '-', active: true, sortOrder: 6, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-8', categoryId: 'medical-conditions', code: 'MC008', name: 'Rapid Weight Loss', description: '-', active: true, sortOrder: 7, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-9', categoryId: 'medical-conditions', code: 'MC009', name: 'Radiation Therapy', description: '-', active: true, sortOrder: 8, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-10', categoryId: 'medical-conditions', code: 'MC010', name: 'Joint Replacement or Implant', description: '-', active: true, sortOrder: 9, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-11', categoryId: 'medical-conditions', code: 'MC011', name: 'Heart Surgery', description: '-', active: true, sortOrder: 10, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-12', categoryId: 'medical-conditions', code: 'MC012', name: 'Heart Attack', description: '-', active: true, sortOrder: 11, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-13', categoryId: 'medical-conditions', code: 'MC013', name: 'Heart Disease', description: '-', active: true, sortOrder: 12, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-14', categoryId: 'medical-conditions', code: 'MC014', name: 'Heart Murmur', description: '-', active: true, sortOrder: 13, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-15', categoryId: 'medical-conditions', code: 'MC015', name: 'Hepatitis or Liver Disease', description: '-', active: true, sortOrder: 14, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-16', categoryId: 'medical-conditions', code: 'MC016', name: 'Rheumatic Fever', description: '-', active: true, sortOrder: 15, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-17', categoryId: 'medical-conditions', code: 'MC017', name: 'Allergies', description: '-', active: true, sortOrder: 16, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-18', categoryId: 'medical-conditions', code: 'MC018', name: 'Respiratory Problems', description: '-', active: true, sortOrder: 17, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-19', categoryId: 'medical-conditions', code: 'MC019', name: 'Tuberculosis', description: '-', active: true, sortOrder: 18, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-20', categoryId: 'medical-conditions', code: 'MC020', name: 'Gout or Swollen Ankles', description: '-', active: true, sortOrder: 19, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-21', categoryId: 'medical-conditions', code: 'MC021', name: 'Kidney Disease', description: '-', active: true, sortOrder: 20, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-22', categoryId: 'medical-conditions', code: 'MC022', name: 'Chest Pain', description: '-', active: true, sortOrder: 21, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-23', categoryId: 'medical-conditions', code: 'MC023', name: 'Stroke', description: '-', active: true, sortOrder: 22, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-24', categoryId: 'medical-conditions', code: 'MC024', name: 'Cancer or Tumors', description: '-', active: true, sortOrder: 23, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-25', categoryId: 'medical-conditions', code: 'MC025', name: 'Anemia', description: '-', active: true, sortOrder: 24, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-26', categoryId: 'medical-conditions', code: 'MC026', name: 'Angina', description: '-', active: true, sortOrder: 25, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-27', categoryId: 'medical-conditions', code: 'MC027', name: 'Asthma', description: '-', active: true, sortOrder: 26, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-28', categoryId: 'medical-conditions', code: 'MC028', name: 'Bleeding Problems', description: '-', active: true, sortOrder: 27, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-29', categoryId: 'medical-conditions', code: 'MC029', name: 'Emphysema', description: '-', active: true, sortOrder: 28, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-30', categoryId: 'medical-conditions', code: 'MC030', name: 'Head Injuries', description: '-', active: true, sortOrder: 29, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-31', categoryId: 'medical-conditions', code: 'MC031', name: 'Arthritis or Rheumatism', description: '-', active: true, sortOrder: 30, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-32', categoryId: 'medical-conditions', code: 'MC032', name: 'Thyroid Problem', description: '-', active: true, sortOrder: 31, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-33', categoryId: 'medical-conditions', code: 'MC033', name: 'Diabetes', description: '-', active: true, sortOrder: 32, updatedAt: '2026-07-12', severity: 'Low' },
  { id: 'mc-34', categoryId: 'medical-conditions', code: 'MC034', name: 'Others', description: '-', active: true, sortOrder: 33, updatedAt: '2026-07-12', severity: 'Low' },

  { id: 'habit-1', categoryId: 'dental-habits', code: 'DH001', name: 'Night-time Bottle Feeding', description: '-', active: true, sortOrder: 0, updatedAt: '2026-07-12', category: 'Feeding' },
  { id: 'habit-2', categoryId: 'dental-habits', code: 'DH002', name: 'Thumb Sucking', description: '-', active: true, sortOrder: 1, updatedAt: '2026-07-12', category: 'Oral Habit' },
  { id: 'habit-3', categoryId: 'dental-habits', code: 'DH003', name: 'Tongue Thrusting', description: '-', active: true, sortOrder: 2, updatedAt: '2026-07-12', category: 'Oral Habit' },
  { id: 'habit-4', categoryId: 'dental-habits', code: 'DH004', name: 'Teeth Grinding', description: '-', active: true, sortOrder: 3, updatedAt: '2026-07-12', category: 'Parafunction' },
  { id: 'habit-5', categoryId: 'dental-habits', code: 'DH005', name: 'Nail Biting', description: '-', active: true, sortOrder: 4, updatedAt: '2026-07-12', category: 'Parafunction' },
  { id: 'habit-6', categoryId: 'dental-habits', code: 'DH006', name: 'Mouth Breathing', description: '-', active: true, sortOrder: 5, updatedAt: '2026-07-12', category: 'Airway' },
  { id: 'habit-7', categoryId: 'dental-habits', code: 'DH007', name: 'Smoking', description: '-', active: true, sortOrder: 6, updatedAt: '2026-07-12', category: 'Risk' },

  { id: 'tag-1', categoryId: 'risk-tags', code: 'TAG001', name: 'CAVSU', description: '-', active: true, sortOrder: 0, updatedAt: '2026-07-12', color: '#0ea5e9', priority: 'Standard' },
  { id: 'tag-2', categoryId: 'risk-tags', code: 'TAG002', name: 'Liwayway', description: '-', active: true, sortOrder: 1, updatedAt: '2026-07-12', color: '#14b8a6', priority: 'Standard' },
  { id: 'tag-3', categoryId: 'risk-tags', code: 'TAG003', name: 'Yazaki', description: '-', active: true, sortOrder: 2, updatedAt: '2026-07-12', color: '#f59e0b', priority: 'Standard' },
  { id: 'tag-4', categoryId: 'risk-tags', code: 'TAG004', name: 'LabXpert-OPD', description: '-', active: true, sortOrder: 3, updatedAt: '2026-07-12', color: '#6366f1', priority: 'Standard' },
  { id: 'tag-5', categoryId: 'risk-tags', code: 'TAG005', name: 'Braces', description: 'Braces Patients', active: true, sortOrder: 4, updatedAt: '2026-07-12', color: '#8b5cf6', priority: 'High' },
  { id: 'tag-6', categoryId: 'risk-tags', code: 'TAG006', name: 'Oral Prophylaxis', description: '-', active: true, sortOrder: 5, updatedAt: '2026-07-12', color: '#10b981', priority: 'Standard' },
  { id: 'tag-7', categoryId: 'risk-tags', code: 'TAG007', name: 'Lyceum', description: '-', active: true, sortOrder: 6, updatedAt: '2026-07-12', color: '#ec4899', priority: 'Standard' }
];
